/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.philfood;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vjanr
 */
public class POS extends javax.swing.JFrame {
    int sum = 0;
    int qty;
    int price;
    int total;
    int change = 0;

    public POS(String name) {
        initComponents();
        Image icon = new ImageIcon(this.getClass().getResource("/images/icon.png")).getImage();
        this.setIconImage(icon); 
        lblBarista.setText(name);

    }

    private POS() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBarista = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnLechon = new javax.swing.JButton();
        btnCrispyPata = new javax.swing.JButton();
        btnSinugba = new javax.swing.JButton();
        btnTinola = new javax.swing.JButton();
        btnSinigang = new javax.swing.JButton();
        btnBulalo = new javax.swing.JButton();
        btnBistek = new javax.swing.JButton();
        btnCaldereta = new javax.swing.JButton();
        btnGiniling = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnHalohalo = new javax.swing.JButton();
        btnSagotGulaman = new javax.swing.JButton();
        btnTaho = new javax.swing.JButton();
        btnBukoSalad = new javax.swing.JButton();
        btnBukoPandan = new javax.swing.JButton();
        btnTapioca = new javax.swing.JButton();
        btnMangoShake = new javax.swing.JButton();
        btnAvocadoShake = new javax.swing.JButton();
        btnSikwate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        txtChange = new javax.swing.JTextField();
        btnVoid = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("SF UI  Text", 1, 36)); // NOI18N
        jLabel1.setText("PhilFood");

        jLabel2.setText("Welcome ,");

        lblBarista.setText("Null");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBarista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(lblBarista))
                            .addGap(16, 16, 16)))))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLechon.setText("Lechon");
        btnLechon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLechonActionPerformed(evt);
            }
        });

        btnCrispyPata.setText("Crispy Pata");
        btnCrispyPata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrispyPataActionPerformed(evt);
            }
        });

        btnSinugba.setText("Sinugba");
        btnSinugba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinugbaActionPerformed(evt);
            }
        });

        btnTinola.setText("Tinola");
        btnTinola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinolaActionPerformed(evt);
            }
        });

        btnSinigang.setText("Sinigang");
        btnSinigang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinigangActionPerformed(evt);
            }
        });

        btnBulalo.setText("Bulalo");
        btnBulalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBulaloActionPerformed(evt);
            }
        });

        btnBistek.setText("Bistek");
        btnBistek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBistekActionPerformed(evt);
            }
        });

        btnCaldereta.setText("Caldereta");
        btnCaldereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalderetaActionPerformed(evt);
            }
        });

        btnGiniling.setText("Giniling");
        btnGiniling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGinilingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBistek, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnCaldereta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnTinola, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSinigang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnLechon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(btnCrispyPata, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSinugba, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBulalo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiniling, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLechon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCrispyPata, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinugba, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinola, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinigang, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBulalo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBistek, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaldereta, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGiniling, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHalohalo.setText("Halo-Halo");
        btnHalohalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHalohaloActionPerformed(evt);
            }
        });

        btnSagotGulaman.setText("Sago't Gulaman");
        btnSagotGulaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSagotGulamanActionPerformed(evt);
            }
        });

        btnTaho.setText("Taho");
        btnTaho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTahoActionPerformed(evt);
            }
        });

        btnBukoSalad.setText("Buko Salad");
        btnBukoSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukoSaladActionPerformed(evt);
            }
        });

        btnBukoPandan.setText("Buko Pandan");
        btnBukoPandan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukoPandanActionPerformed(evt);
            }
        });

        btnTapioca.setText("Tapioca");
        btnTapioca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTapiocaActionPerformed(evt);
            }
        });

        btnMangoShake.setText("Mango Shake");
        btnMangoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMangoShakeActionPerformed(evt);
            }
        });

        btnAvocadoShake.setText("Avocado Shake");
        btnAvocadoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvocadoShakeActionPerformed(evt);
            }
        });

        btnSikwate.setText("Sikwate");
        btnSikwate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSikwateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBukoSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBukoPandan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMangoShake, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAvocadoShake, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnHalohalo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSagotGulaman, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTaho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSikwate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTapioca, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHalohalo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaho, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSagotGulaman, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBukoSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBukoPandan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTapioca, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMangoShake, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSikwate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAvocadoShake, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("SF UI  Text", 1, 24)); // NOI18N
        jLabel3.setText("Food");

        jLabel4.setFont(new java.awt.Font("SF UI  Text", 1, 24)); // NOI18N
        jLabel4.setText("Drinks");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SF UI  Text", 1, 24)); // NOI18N
        jLabel5.setText("Total :");

        jLabel6.setFont(new java.awt.Font("SF UI  Text", 1, 24)); // NOI18N
        jLabel6.setText("Cash :");

        jLabel7.setFont(new java.awt.Font("SF UI  Text", 1, 24)); // NOI18N
        jLabel7.setText("Change :");

        txtTotal.setEditable(false);

        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });

        txtChange.setEditable(false);

        btnVoid.setBackground(new java.awt.Color(255, 0, 0));
        btnVoid.setFont(new java.awt.Font("SF UI  Text", 1, 36)); // NOI18N
        btnVoid.setText("VOID");
        btnVoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoidActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 255, 51));
        btnPrint.setFont(new java.awt.Font("SF UI  Text", 1, 36)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChange)
                                    .addComponent(txtCash))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLechonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLechonActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnLechon.getText(),
            price = 250,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }   
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnLechonActionPerformed

    private void btnCrispyPataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrispyPataActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnCrispyPata.getText(),
            price = 190,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnCrispyPataActionPerformed

    private void btnSinugbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinugbaActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnSinugba.getText(),
            price = 130,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnSinugbaActionPerformed

    private void btnTinolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinolaActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnTinola.getText(),
            price = 190,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnTinolaActionPerformed

    private void btnSinigangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinigangActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnSinigang.getText(),
            price = 120,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnSinigangActionPerformed

    private void btnBulaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBulaloActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnBulalo.getText(),
            price = 230,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnBulaloActionPerformed

    private void btnBistekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBistekActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnBistek.getText(),
            price = 100,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnBistekActionPerformed

    private void btnCalderetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalderetaActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnCaldereta.getText(),
            price = 130,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnCalderetaActionPerformed

    private void btnGinilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGinilingActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnGiniling.getText(),
            price = 100,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnGinilingActionPerformed

    private void btnHalohaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHalohaloActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnHalohalo.getText(),
            price = 70,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnHalohaloActionPerformed

    private void btnSagotGulamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSagotGulamanActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnSagotGulaman.getText(),
            price = 30,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnSagotGulamanActionPerformed

    private void btnTahoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTahoActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnTaho.getText(),
            price = 30,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnTahoActionPerformed

    private void btnBukoSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukoSaladActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnBukoSalad.getText(),
            price = 70,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnBukoSaladActionPerformed

    private void btnBukoPandanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukoPandanActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnBukoPandan.getText(),
            price = 30,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnBukoPandanActionPerformed

    private void btnTapiocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTapiocaActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnTapioca.getText(),
            price = 70,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnTapiocaActionPerformed

    private void btnMangoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMangoShakeActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnMangoShake.getText(),
            price = 90,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnMangoShakeActionPerformed

    private void btnAvocadoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvocadoShakeActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnAvocadoShake.getText(),
            price = 900,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));    }//GEN-LAST:event_btnAvocadoShakeActionPerformed

    private void btnSikwateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSikwateActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[] {
            btnSikwate.getText(),
            price = 50,
            qty = 1,
            total = qty * price,
        });
        
            sum = 0;
            for(int i = 0; i < jTable1.getRowCount(); i++) {
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
    txtTotal.setText(Integer.toString(sum));    }//GEN-LAST:event_btnSikwateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++) {
            price = Integer.parseInt(model.getValueAt(i, 1).toString());
            qty = Integer.parseInt(model.getValueAt(i, 2).toString());
            if(qty > 1) {
                total = qty * price;
                model.setValueAt(total, i, 3);
                
            }
            txtTotal.setText("0");
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            txtTotal.setText(Integer.toString(sum));
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        int cash = Integer.parseInt(txtCash.getText());
        int total = Integer.parseInt(txtTotal.getText());

        if (cash < total) {
            JOptionPane.showMessageDialog(this, "Insufficient Funds", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int change = cash - total;
        txtChange.setText(String.valueOf(change));
    }//GEN-LAST:event_txtCashActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        String total = txtTotal.getText();
        String cash = txtCash.getText();
        String change = txtChange.getText();

        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Comma-separated values", "csv");
        fileChooser.setFileFilter(filter);

        int returnValue = fileChooser.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            if (!filePath.endsWith(".csv")) {
                filePath += ".csv";
            }
            try {
                FileWriter fw = new FileWriter(filePath);
                BufferedWriter bw = new BufferedWriter(fw);

                bw.write("Total,Cash,Change\n");
                bw.write(total + "," + cash + "," + change + "\n");

                bw.close();
                fw.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnVoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidActionPerformed
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        sum = 0;
        txtTotal.setText(Integer.toString(sum));
        txtCash.setText(Integer.toString(sum));
        txtChange.setText(Integer.toString(sum));
    }//GEN-LAST:event_btnVoidActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        String total = txtTotal.getText();
        String cash = txtCash.getText();
        String change = txtChange.getText();
        if (total.isEmpty() || cash.isEmpty() || change.isEmpty() || total.equals("0") ||cash.equals("0")||change.equals("0")) {
            JOptionPane.showMessageDialog(this, "Error: Total, Cash, and Change fields must not be empty.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            String name = lblBarista.getText();
            Receipt receiptWindow = new Receipt(model, name, total, cash, change);
            receiptWindow.setLocationRelativeTo(null);
            receiptWindow.setVisible(true);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            String filePath = "DTR.txt";
            BufferedReader reader = new BufferedReader(new FileReader(filePath));
            String line;
            String currentTime = new SimpleDateFormat("HH:mm:ss").format(new Date()); 

            StringBuilder sb = new StringBuilder();
            while ((line = reader.readLine()) != null) {
                if (line.matches(".+,\\d{2}:\\d{2}:\\d{2},\\d{2}:\\d{2}:\\d{2}")) { 
                    sb.append(line).append("\n");
                } else if (line.matches(".+,\\d{2}:\\d{2}:\\d{2},.*")) { 
                    line = line.trim();
                    int commaIndex = line.lastIndexOf(",");
                    line = line.substring(0, commaIndex+1) + currentTime;
                    sb.append(line).append("\n");
                } else {
                    sb.append(line).append("\n");
                }
            }
            reader.close();

            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
            writer.write(sb.toString());
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        System.exit(0);

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvocadoShake;
    private javax.swing.JButton btnBistek;
    private javax.swing.JButton btnBukoPandan;
    private javax.swing.JButton btnBukoSalad;
    private javax.swing.JButton btnBulalo;
    private javax.swing.JButton btnCaldereta;
    private javax.swing.JButton btnCrispyPata;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnGiniling;
    private javax.swing.JButton btnHalohalo;
    private javax.swing.JButton btnLechon;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMangoShake;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSagotGulaman;
    private javax.swing.JButton btnSikwate;
    private javax.swing.JButton btnSinigang;
    private javax.swing.JButton btnSinugba;
    private javax.swing.JButton btnTaho;
    private javax.swing.JButton btnTapioca;
    private javax.swing.JButton btnTinola;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVoid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBarista;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChange;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
